name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: A clear description of the feature or improvement.
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
      description: What problem does this solve or what workflow does it improve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds or considered other approaches?
    validations:
      required: false
